# numpy practice

In [2]:
import numpy as np

## 1. numpy & pandas 的优点
- 运算速度快：numpy 和 pandas 都是采用 C 语言编写, pandas 又是基于 numpy, 是 numpy 的升级版本，会比 python 自带的字典或者列表快好多。
- 消耗资源少：NumPy是在一个连续的内存块中存储数据， 独立于其他Python内置对象，NumPy的C语言编写的算法库可以操作内存， 而不必进行类型检查或其它前期工作。 比起Python的内置序列， NumPy数组使用的内存更少。

In [11]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print(my_arr.size)
print(len(my_list))
# 各个序列分别乘以2

1000000
1000000


In [12]:
%%time 
# 基于numpy
for i in range(10):
    my_arr = my_arr*2

Wall time: 34.2 ms


In [13]:
%%time 
# 基于python
for i in range(10):
    my_list = [x*2 for x in my_list]

Wall time: 1.34 s


## 2. numpy 里的数据类型
其实数组中的数据类型可以不唯一

|基本类型|可用的**Numpy**类型|备注
|--|--|--
|布尔型|`bool`|占1个字节
|整型|`int8, int16, int32, int64, int128, int`| `int` 跟**C**语言中的 `long` 一样大
|无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`| `uint` 跟**C**语言中的 `unsigned long` 一样大
|浮点数| `float16, float32, float64, float, longfloat`|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
|复数| `complex64, complex128, complex, longcomplex`| 默认为 `complex128` ，即实部虚部都为双精度
|字符串| `string, unicode` | 可以使用 `dtype=S4` 表示一个4字节字符串的数组
|对象| `object` |数组中可以使用任意值|
|Records| `void` ||
|时间| `datetime64, timedelta64` ||  

### 2.1 使用ndarray的astype方法对数据类型进行转换
**注意**：astype总会创建一个新的数组(a copy of the data)
#### 整数转浮点

In [2]:
# 整数转浮点
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


#### 浮点数转换成整数
小数部分将会被截取删除
  
#### 字符串转数字

In [6]:
numerical_string = np.array(['1.22','333','34.4'])
print(numerical_string.dtype)
print(numerical_string)

num = numerical_string.astype(float)
print(num.dtype)
print(num)

<U4
['1.22' '333' '34.4']
float64
[  1.22 333.    34.4 ]


## 3. ndarray 属性
NumPy最重要的一个特点就是其N维数组对象（ 即ndarray）,该对象是一个快速而灵活的大数据集容器。 你可以利用这种数组对整块数据执行一些数学运算， 其语法跟标量元素之间的运算一样。  
ndarray是一个通用的同构数据多维容器， 也就是说， 其中的所有元素必须是相同类型的。 
**每个数组都有一个shape（ 一个表示各维度大小的元组） 和一个dtype（ 一个用于说明数组数据类型的对象） ：**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#列表转化为矩阵
array=np.array([[1,2,4],[1,3,3],[2,2,3]]) 
print(array)
print(type(array))
print("矩阵维度：number of dim：",array.ndim) #矩阵维度
print("矩阵的shape：",array.shape)#行数和列数
print("元素的个数：",array.size)#矩阵的元素个数
print("查看每个元素所占字节：",array.itemsize)

[[1 2 4]
 [1 3 3]
 [2 2 3]]
<class 'numpy.ndarray'>
矩阵维度：number of dim： 2
矩阵的shape： (3, 3)
元素的个数： 9
查看每个元素所占字节： 4


## 4. 创建ndarray
### 4.1 使用array函数创建ndarray
np.array会尝试为新建的这个数组推断出一个较为合适的数据类型,当然也可以直接指定数据类型

In [14]:
print("------------自动选择数据类型---------")
a=np.array([1,2,3])
print("np.array([1,2,3])=",a)
print("a.dtype=",a.dtype)
print()

#--------------------------------------------------------------------------指定数据类型(精确度与内存之间的取舍!------------
print("------------指定数据类型(精确度与内存之间的取舍!---------")
a1=np.array([1,1,2],dtype=np.int)
print("np.array([1,1,2],dtype=np.int)默认64位int：",a1)

a2=np.array([1,1,2],dtype=np.int32)
print("np.array([1,1,2],dtype=np.int32) 输出32位int：",a1)

a = np.array([2,23,4],dtype=np.float)
print("a=np.array([2,23,4],dtype=np.float)，a.dtype=",a.dtype)

np.array([1,2,3])= [1 2 3]

------------指定数据类型(精确度与内存之间的取舍!---------
np.array([1,1,2],dtype=np.int)默认64位int： [1 1 2]
np.array([1,1,2],dtype=np.int32) 输出32位int： [1 1 2]
a=np.array([2,23,4],dtype=np.float)，a.dtype= float64


### 4.2 使用其他函数创建ndarray

In [15]:
#---------------------创建特定数据---------------
print("--------------创建特定数据---------------")
#数据全为0，3行4列
print("-----zeros()函数")
tmp=np.zeros((3,4))
print("np.zeros((3,4)):",tmp,",tmp.dtype:",tmp.dtype)
print()

#创建全一数组, 同时也能指定这些特定数据的 dtype
print("-----ones()函数")
tmp=np.ones((3,4),dtype=np.int)
print('np.ones((3,4),dtype=np.int)=')
print(tmp)
print()

#创建全空数组, 其实每个值都是接近于零的数:
print("-----empty()函数")
tmp=np.empty((3,4))
print("tmp=np.empty((3,4))=",tmp,"tmp.dtype:",tmp.dtype)
print()

#用 arange 创建连续数组
print("-----arange()函数")
tmp=np.arange(10,20,2)#10-19 的数据，2步长    ## 前闭后开区间
print("tmp=np.arange(10,20,2)=",tmp,"前闭后开区间")
tmp=np.arange(10)#从0开始10个整数
print("np.arange(10)=",tmp,"从0开始10个整数")
tmp=np.arange(14,2, -1)
print("np.arange(14,2, -1)=",np.arange(14,2, -1))
print()

print("-----reshape()函数")
print("reshape 1*10数据的形状：np.arange(10).reshape((2,5))=",np.arange(10).reshape((2,5)))
print()

    #用 linspace 创建线段型数据:开始端1，结束端10，且分割出20个数据点
print("-----linespace()函数")
tmp=np.linspace(1,10,20)
print("np.linspace(1,10,20):")
print(tmp)

--------------创建特定数据---------------
-----zeros()函数
np.zeros((3,4)): [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] ,tmp.dtype: float64

-----ones()函数
np.ones((3,4),dtype=np.int)=
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

-----empty()函数
tmp=np.empty((3,4))= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] tmp.dtype: float64

-----arange()函数
tmp=np.arange(10,20,2)= [10 12 14 16 18] 前闭后开区间
np.arange(10)= [0 1 2 3 4 5 6 7 8 9] 从0开始10个整数
np.arange(14,2, -1)= [14 13 12 11 10  9  8  7  6  5  4  3]

-----reshape()函数
reshape 1*10数据的形状：np.arange(10).reshape((2,5))= [[0 1 2 3 4]
 [5 6 7 8 9]]

-----linespace()函数
np.linspace(1,10,20):
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 5. Numpy Array运算
numpy一大优点是不用编写循环即可对数据执行批量运算，NumPy用户称其为vectorization：大小相等的数组之间的任何算术运算都会将运算应用到元素级：
### 5.1 加减乘除-幂-三角函数

In [9]:
# 加减乘除-幂-三角函数
a=np.array([1,2,3,4])
b=np.arange(4)
print('a:',a)
print('b:',b)

print("a-b=",a-b)
print("与标量做加法：a+1=",a+1)

# 乘法
print("a*b=",a*b)
print()

# 除法
print('与标量做除法：1/a=',1/a)
print()

# 幂的表示是**
print("b的3次方b**3：",b**3)

#三角函数运算
c=10*np.sin(b)
print("c=np.sin(b)*10=",c)

a: [1 2 3 4]
b: [0 1 2 3]
a-b= [1 1 1 1]
与标量做加法：a+1= [2 3 4 5]
a*b= [ 0  2  6 12]

与标量做除法：1/a= [1.         0.5        0.33333333 0.25      ]

b的3次方b**3： [ 0  1  8 27]
c=np.sin(b)*10= [0.         8.41470985 9.09297427 1.41120008]


### 5.2 比较操作
Operations between differently sized arrays is called broadcasting. 

In [10]:
#矩阵与某个值比较并返回bool值
print("np.sin(c)*10>3 ?",c>3)


np.sin(c)*10>3 ? [False  True  True False]


### 5.3 Indexing and Slicing（索引和切片）
#### 一维数组索引和切片
切片是前闭后开区间

In [34]:
arr1 = np.arange(10)
print(arr1[5:8])
print()



print('给slice赋值该值会自动传播到整个选区，并且会直接反映到源数组上')
arr1[5:8]=0
print(arr1)

[5 6 7]

给slice赋值该值会自动传播到整个选区，并且会直接反映到源数组上
[0 1 2 3 4 0 0 0 8 9]


#### 多维数组索引和切片

In [37]:
arr2 = np.arange(2,14).reshape((3,4))
print('arr2:')
print(arr2)
print()

print('多维数组一维切片arr2[1:3]:')
print(arr2[1:3])
print()

print('多维数组多维切片arr2[:3,1:]:')
print(arr2[:3,1:])
print()

print('索引选取单个元素的两种方式：')
print('arr2[2,2]=',arr2[2,2])
print('arr2[2][2]=',arr2[2][2])

arr2:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

多维数组一维切片arr2[1:3]:
[[ 6  7  8  9]
 [10 11 12 13]]

多维数组多维切片arr2[:3,1:]:
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]

索引选取单个元素的两种方式：
arr2[2,2]= 12
arr2[2][2]= 12


In [5]:

print('(---------------矩阵部分----------------')
#创建一个二维矩阵
a=np.array([[1,1],[0,1]])
b=np.arange(1,5).reshape((2,2))
print("a:",a)
print("b:",b)
print()

#矩阵点乘
print("dot函数：当两个参数都为一维数组时，计算的是点积；当两个参数是二维数组时，计算的是矩阵乘积")
print("np.dot(a,b):\n",np.dot(a,b))
c=a*b
#矩阵逐个相乘
print("a*b的两个矩阵行列大小必须一致")
print("c=a*b=\n",c)

# 以行或列为单位求和 以及 查找极值：
print("np.sum(c)：",np.sum(c))
print("求最大值np.max(c)：",np.max(c))
print()

print("以行或列为单位求和 以及 查找极值：")
print("axis的值为0的时候，将会以列作为查找单元:")
print("np.sum(c,axis=0)=",np.sum(c,axis=0))

print("\naxis的值为1的时候，将会以行作为查找单元:")
print("np.max(c,axis=1) =",np.max(c,axis=1))

# 全部元素的乘积
print("-----------\n全部元素的乘积 b.prod()=",b.prod())

a: [1 2 3 4]
b: [0 1 2 3]
a-b= [1 1 1 1]
a+1= [2 3 4 5]
a*b= [ 0  2  6 12]

b的3次方b**3： [ 0  1  8 27]
c=np.sin(b)*10= [0.         8.41470985 9.09297427 1.41120008]

np.sin(c)*10>3 ? [False  True  True False]
(---------------矩阵部分----------------
a: [[1 1]
 [0 1]]
b: [[1 2]
 [3 4]]

dot函数：当两个参数都为一维数组时，计算的是点积；当两个参数是二维数组时，计算的是矩阵乘积
np.dot(a,b):
 [[4 6]
 [3 4]]
a*b的两个矩阵行列大小必须一致
c=a*b=
 [[1 2]
 [0 4]]
np.sum(c)： 7
求最大值np.max(c)： 4

以行或列为单位求和 以及 查找极值：
axis的值为0的时候，将会以列作为查找单元:
np.sum(c,axis=0)= [1 6]

axis的值为1的时候，将会以行作为查找单元:
np.max(c,axis=1) = [2 4]
-----------
全部元素的乘积 b.prod()= 24


In [87]:
#求对应元素的索引
A = np.arange(2,14).reshape((3,4))
print("A:",A)

print("--------------argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引--------------")
print("np.argmin(A)",np.argmin(A))    # 0
print("np.argmax(A)",np.argmax(A))    # 1
print()

# 指定求和的维度
print("-------------指定求和的维度 A.sum(axis=0)-------------------")
print(A.sum(axis=0))

#均值
print("-----------求均值--------------")
print("A.mean()=",A.mean())
print("average计算加权平均数（average(a, axis = 0, weights=[1,2])）")
print("np.average(A)=",np.average(A))
print()

#求解中位数
print("--------求中位数-------------")
print("np.median(A)=",np.median(A))   
print()

#cumsum()累加函数
print("-----------cumsum()累加函数---------------")
print("np.cumsum(A)=",np.cumsum(A)) 
# 累差运算函数
print("-----------diff累差运算函数-------------")
print("np.diff(A)输出前一项与后一项的差：")
print(np.diff(A))
print()

# nonzero函数
print("-----所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵----")
print("np.nonzero(A)",np.nonzero(A))  
print()


#对每一行进行从小到大排序
print("------对每一行进行从小到大排序-----")
print("np.sort(A)") 
print(np.sort(A))
print()


#矩阵的转置有两种表示方法
print("------矩阵的转置有两种表示方法------")
print("np.transpose(A):")
print(np.transpose(A))
print("A.T:")
print(A.T)
print('''-------------------如果是一维的数组则无法转置(使用shape后可以发现，它其实不具有矩阵的属性)--------------
                           解决办法：①使用reshape使其强行具有矩阵的属性(注意!!!要进行赋值否则不会发生更改)
                                     ②这个时候可以通过np.newaxis()实现想要的效果

''')
A = np.array([1,1,1])
print("A:")
print(A)
print("A.T:")
print(A.T)
print("A[np.newaxis,:]")
print(A[np.newaxis,:])



#clip()函数把超过区间的统统改成区间极值
print("-------clip()函数把超过区间的统统改成区间极值----")
print("A:",A)
print("np.clip(A,5,9):")
print()
print(np.clip(A,5,9))    

A: [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
--------------argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引--------------
np.argmin(A) 0
np.argmax(A) 11

-------------A.sum(axis=0)-------------------
[18 21 24 27]
-----------求均值--------------
A.mean()= 7.5
average计算加权平均数（如果有权重weight的话）
np.average(A)= 7.5

--------求中位数-------------
np.median(A)= 7.5

-----------cumsum()累加函数---------------
np.cumsum(A)= [ 2  5  9 14 20 27 35 44 54 65 77 90]
-----------diff累差运算函数-------------
np.diff(A)输出前一项与后一项的差：
[[1 1 1]
 [1 1 1]
 [1 1 1]]

-----所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵----
np.nonzero(A) (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

------对每一行进行从小到大排序-----
np.sort(A)
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

------矩阵的转置有两种表示方法------
np.transpose(A):
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
A.T:
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
-------------------如果是一维的数组则无法转置(使用shape后可以发现，它其实不具有矩阵的属性)-----------

## 随机函数random
numpy.random.rand(d0,d1,…,dn)和numpy.random.random(tuple) 一样的效果，返回值为指定维度的array  
numpy.random.randn(d0,d1,…,dn)返回指定维度的**正态分布**的array  

In [3]:
# numpy.random.rand(d0,d1,…,dn)
# numpy.random.random(tuple) 一样的效果
'''
    rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
    dn表格每个维度
    返回值为指定维度的array
'''
a=np.random.rand(4,3,2)
print("-----------------------np.random.rand(4,3,2) 返回[0,1)之间的数据----------------------:")
print(a)
print()

b=np.random.random((4,3,2))
print("-----------------------np.random.random((4,3,2)) [0,1)之间的数据-------------------:")
print(b)


# numpy.random.randn(d0,d1,…,dn)
'''
    randn函数返回一个或一组样本，具有标准正态分布。
    dn表格每个维度
    返回值为指定维度的array
'''
print("\n-----------------np.random.randn(3)标准正态分布----------------------------")
print(np.random.randn(3))

# numpy.random.randint(low, high=None, size=None, dtype=’l’)
'''
    返回随机整数，范围区间为[low,high），包含low，不包含high
    参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
    high没有填写时，默认生成随机数的范围是[0，low)
'''
print("\n-----------------np.random.randint(-5,5,size=(2,2))-------------------")
print(np.random.randint(-5,5,size=(2,2)))


# numpy.random.choice(a, size=None, replace=True, p=None)
'''
    从给定的一维数组中生成随机数
    参数： a为一维数组类似数据或整数；a为整数时，对应的一维数组为np.arange(a)
    size为数组维度；
    当replace为False时，生成的随机数不能有重复的数值;
    p为数组中的数据出现的概率
'''
print("--------np.random.choice(5, 3, replace=False,p=[0.1, 0, 0.3, 0.6, 0])----------")
print (np.random.choice(5, 3, replace=False,p=[0.1, 0, 0.3, 0.6, 0]))
print()

# numpy.random.seed()
'''
    使得随机数据可预测。
    当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数
'''
print("-------------设置np.random.seed(0)----------------")
np.random.seed(0)
print("seed0:",np.random.rand(5))
print("seed0:",np.random.rand(5))
print("-------------设置np.random.seed(1)----------------")
np.random.seed(1)
print("seed1:",np.random.rand(5))
print("-------------设置np.random.seed(0)----------------")
np.random.seed(0)
print("seed0:",np.random.rand(5))
print("seed0:",np.random.rand(5))

-----------------------np.random.rand(4,3,2) 返回[0,1)之间的数据----------------------:
[[[2.27178706e-01 2.11305569e-01]
  [1.02270616e-01 8.63580323e-01]
  [9.00071367e-01 2.81225925e-01]]

 [[2.37288405e-01 6.92386132e-01]
  [7.27027874e-04 6.75819406e-01]
  [8.43536813e-01 6.87919419e-02]]

 [[2.04655891e-02 9.94605298e-01]
  [6.92749850e-01 3.52731894e-01]
  [4.37759725e-02 8.45112819e-01]]

 [[5.01489250e-01 5.67132662e-01]
  [1.90757070e-01 7.15065711e-01]
  [3.42361373e-02 2.59206583e-02]]]

-----------------------np.random.random((4,3,2)) [0,1)之间的数据-------------------:
[[[0.17329935 0.91678093]
  [0.397611   0.46898494]
  [0.33415779 0.29485666]]

 [[0.19626869 0.21709674]
  [0.02732723 0.64304868]
  [0.16978553 0.9078018 ]]

 [[0.01199198 0.90276851]
  [0.29588148 0.79062629]
  [0.65589202 0.68199416]]

 [[0.10429672 0.18931486]
  [0.85047733 0.9347346 ]
  [0.16322868 0.44358829]]]
-----------------np.random.randn(3)标准正态分布----------------------------
[ 0.36374549  0.20456573 -2.3392

## numpy索引和切片

In [11]:
#-----------一维索引-------------------
print("----------------一维索引---------------------")
A = np.arange(3,15)
print('A=',A)
print()

# 花式索引
print("---------花式索引之 用整数自定义索引位置(本质格式是A[[]])-----------------")
indices = [1, 2, -3]
print('A[indices]=',A[indices])

print("或者用布尔表达式生成满足条件的 mask(也可创建类型为布尔值的array作为mask)")
mask= A>=7
print('mask=',mask)
print("A[mask]:")
print(A[mask])
print()

print("A[3]:",A[3]) 
A=A.reshape(3,4)
print("A:",A)
print("实际上A[2]输出第'2'行：",A[2])
print()

print("------------切片：①最右边索引是-1 ②完整格式为seq[start:end:step]------------")
print("提取第一个元素：A[0]=",A[0])
print("提取前两个元素：A[:2]=",A[:2])
print('A[0:4:2]=\n',A[0:4:2])
a=np.arange(4)
print("a=np.arange(4)=",a)
print("提取后两个元素：a[-2::]=",a[-2:])
print('a[:2]=',a[:2])
print("np.arange(3,15)[::3]=",np.arange(3,15)[::3])
print()
      

print("----------------二维索引-----------------")
#-----------二维索引--------------
print("二维索引两种表示方法A[0,0]:",A[0,0],", A[0][0]:",A[0][0])
print("A[0,0:3]:",A[0,0:4])
print("A[0:2,0]:",A[0:3,0])
print()


print("-------利用for函数进行 行迭代-----------")
for row in A:     
    print(row)

for column in A.T:     
    print(column)
print()


print("--------flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列。将多维的矩阵进行展开成1行的数列就可以进行  逐项迭代了----")
print(A.flatten())  

#flat是一个迭代器，本身是一个object属性
for item in A.flat:     
    print(item)


----------------一维索引---------------------
A= [ 3  4  5  6  7  8  9 10 11 12 13 14]

---------花式索引之 用整数自定义索引位置(本质格式是A[[]])-----------------
A[indices]= [ 4  5 12]
或者用布尔表达式生成满足条件的 mask(也可创建类型为布尔值的array作为mask)
mask= [False False False False  True  True  True  True  True  True  True  True]
A[mask]:
[ 7  8  9 10 11 12 13 14]

A[3]: 6
A: [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
实际上A[2]输出第'2'行： [11 12 13 14]

------------切片：①最右边索引是-1 ②完整格式为seq[start:end:step]------------
提取第一个元素：A[0]= [3 4 5 6]
提取前两个元素：A[:2]= [[ 3  4  5  6]
 [ 7  8  9 10]]
A[0:4:2]=
 [[ 3  4  5  6]
 [11 12 13 14]]
a=np.arange(4)= [0 1 2 3]
提取后两个元素：a[-2::]= [2 3]
a[:2]= [0 1]
np.arange(3,15)[::3]= [ 3  6  9 12]

----------------二维索引-----------------
二维索引两种表示方法A[0,0]: 3 , A[0][0]: 3
A[0,0:3]: [3 4 5 6]
A[0:2,0]: [ 3  7 11]

-------利用for函数进行 行迭代-----------
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]

--------flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列。将多维的矩阵进行展开成1行的数列就可以进行  逐项迭代了----
[ 3  4  5  

# array 合并

In [10]:
A = np.array([1,1,1])
B = np.array([2,2,2])
# 注意！！！先转换成矩阵
A = A[np.newaxis,:]
B = B[np.newaxis,:]
print("A:")
print(A)
print("B:")
print(B)

print("--------------np.vstack((A,B))上下合并------------------")
C = np.vstack((A,B))  
print("C:",C)
print("A.shape:",A.shape)
print("C.shape:",C.shape)
print()

print("--------------np.hstack((A,B))左右合并------------------")
D = np.hstack((A,B))       # horizontal stack
print()

print("--------------np.concatenate((A,B,B,A),axis=0)对多个矩阵进行合并----------------")
C = np.concatenate((A,B,B,A),axis=0)
print("np.concatenate((A,B,B,A),axis=0)",C)
D = np.concatenate((A,B,B,A),axis=1)
print("np.concatenate((A,B,B,A),axis=1)",D)
print()
print('''numpy没有动态改变数组大小的功能，每次调用conconcatenate时，
系统会重新开辟内存生成一个数组，并将原来的数组复制到新数组中，
这个过程是非常耗时的，所以导致整个程序变得非常缓慢。 
'''
)


A:
[[1 1 1]]
B:
[[2 2 2]]
--------------np.vstack((A,B))上下合并------------------
C: [[1 1 1]
 [2 2 2]]
A.shape: (1, 3)
C.shape: (2, 3)

--------------np.hstack((A,B))左右合并------------------

--------------np.concatenate((A,B,B,A),axis=0)对多个矩阵进行合并----------------
np.concatenate((A,B,B,A),axis=0) [[1 1 1]
 [2 2 2]
 [2 2 2]
 [1 1 1]]
np.concatenate((A,B,B,A),axis=1) [[1 1 1 2 2 2 2 2 2 1 1 1]]

numpy没有动态改变数组大小的功能，每次调用conconcatenate时，
系统会重新开辟内存生成一个数组，并将原来的数组复制到新数组中，
这个过程是非常耗时的，所以导致整个程序变得非常缓慢。 



## Numpy array 分割

In [63]:
A = np.arange(12).reshape((3, 4))
print(A)
print()
# 纵向切割，分成2片
a=np.split(A, 2, axis=1)
print("----------------np.split(A, 2, axis=1)------------------")
print(a)
print(a[1])
print("----------------np.split(A, 3, axis=0)------------------")
print(np.split(A, 3, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

----------------np.split(A, 2, axis=1)------------------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[[ 2  3]
 [ 6  7]
 [10 11]]
----------------np.split(A, 3, axis=0)------------------
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## copy & deep copy

In [23]:
# python对动态变量的传递为引用。那么如何让两个变量赋值后没有关联？
print("使用copy进行复制得到副本")
a = np.arange(4)
print(a.dtype)
b = a.copy() 
c=a

b[0]=1
print("修改b后a不变：",a)
c[0]=1
print("修改c后a变化：",a)


使用copy进行传值
int32
修改b后a不变： [0 1 2 3]
修改c后a变化： [1 1 2 3]
